<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vehicle_launch</name>
  <version>0.1.0</version>
  <description>Launch files for the vehicle component.</description>
  <maintainer email="kiran.g@radskunkworks.com">Kiran Gunathilaka</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>castor_common</exec_depend>
  <exec_depend>castor_vehicle_interface</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
