#!/bin/bash
# stack_sim: the onboard stacks of a simulated team on one machine, one per simulated flight controller, exactly as
# each drone's Pi would run them, plus a ground station. The simulator (make sim-pegasus-ros2) flies the drones.
#
#   components/simulation/stack_sim/stack_sim.sh up [--model NAME/VERSION|DIR] [--tag TAG] [--payload]
#   components/simulation/stack_sim/stack_sim.sh status | down
#
# Mission (the system layer's mission node, from the ground station's domain 20):
#   stack_sim.sh takeoff                waits until every drone is IDLE (printing who is not), sends take-off, then
#                                       follows each drone through PX4 Takeoff and the hand-over to RAPTOR
#   stack_sim.sh goal X Y Z [YAW_DEG]   payload goal, world frame (ENU, m), once the team is READY (payload lifted)
#   stack_sim.sh land                   stop the policy, PX4 Land
#   stack_sim.sh mission | watch        every drone's mission state, once | every change until Ctrl-C
#   stack_sim.sh planning               every drone's planning mode, lift and hand-over check
#
# Everything comes from the model package and the assets (rig_check.py): the model (--model, default models/DEFAULT)
# names the rig it was trained on, components/simulation/assets/config holds that rig and its vehicle; the number of
# drones is the rig's; the take-off height is the model's rig.takeoff_height, but never below the height where the
# cables go taut minus px4_sitl.yaml's takeoff.taut_margin (CASTOR_TAKEOFF_HEIGHT replaces the model's, same floor).
# Start the simulator with the same model (make sim-pegasus-ros2 MODEL=...; both default to models/DEFAULT).
#
# What makes it faithful to N separate Pis on one host:
#   - every robot gets its own ROS 2 domain (drone i: 20+i, payload: after the drones), so no DDS traffic passes
#     between robots inside the host;
#   - every robot has its own zenoh bridge on 127.0.0.1:7447+i, connected to the ground station's bridge (domain 20,
#     127.0.0.1:7447): inter-robot traffic crosses zenoh with the same allow-lists as in flight;
#   - every robot's vehicle container runs its own XRCE agent on UDP 8888+i-1, and PX4 SITL instance i-1 is pointed at
#     it (and at the robot's domain) through environment variables PX4's rcS already reads (written to <state>/px4.env
#     for the simulator to use);
#   - the same images and docker-compose.prod.yml as a Pi, one compose project per robot (castor-stack-sim-<ns>), each
#     with its own run/log/model dirs, the model package copied into every drone's models dir (mounted at
#     /var/lib/castor/models, so it overrides the image's copy, no rebuild).
# docker-compose.stack_sim.yml is all that differs from a Pi: the vehicle component forwards setpoints and commands to
# its PX4 SITL, the mission node runs on the simulator's /clock, and the policy steps once per payload sample.
#
# State lives in $CASTOR_STACK_SIM_DIR (default .stack_sim/ in the repo, gitignored).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"
STATE="${CASTOR_STACK_SIM_DIR:-$ROOT/.stack_sim}"
COMPOSE=(docker compose -f "$ROOT/docker/docker-compose.prod.yml" -f "$ROOT/docker/docker-compose.stack_sim.yml")
PAYLOAD=0 TAG="${CASTOR_TAG:-local}" MODEL=""

cmd="${1:-}"; shift || true
if [ "$cmd" != goal ]; then
    while [ $# -gt 0 ]; do
        case "$1" in
            --payload) PAYLOAD=1; shift ;;
            --tag) TAG="$2"; shift 2 ;;
            --model) MODEL="$2"; shift 2 ;;
            *) echo "unknown option '$1'" >&2; exit 2 ;;
        esac
    done
fi

# A command on the ground station's domain, from the system image, with this directory at /stack_sim.
gcs_run() {
    docker run --rm --network host --ipc host -e ROS_DOMAIN_ID=20 \
        -v "$STATE/gcs/robot.yaml:/etc/castor/robot.yaml:ro" -v "$HERE:/stack_sim:ro" \
        "${CASTOR_REGISTRY:-ghcr.io/fyp-uav-entc-22}/castor-system:$TAG" "$@"
}

robots() { find "$STATE" -mindepth 2 -maxdepth 2 -name stack.env -printf '%h\n' 2>/dev/null | sort; }
drones() { for d in $(robots); do ns=$(basename "$d"); [ "$ns" = payload ] || echo "$ns"; done; }
team() {
    [ -f "$STATE/gcs/robot.yaml" ] || { echo "no stacks: run stack_sim.sh up first" >&2; exit 2; }
    gcs_run python3 /stack_sim/team.py "$@"
}

# robot <namespace> <id> <domain> <bridge port> <agent port> <role> <team index>
write_robot() {
    local ns=$1 id=$2 dom=$3 zport=$4 aport=$5 role=$6 idx=$7 dir="$STATE/$1"
    mkdir -p "$dir/run" "$dir/log" "$dir/models"
    local team="team: {size: $DRONES, index: $idx}"
    [ "$role" = payload ] && team="team: {size: 1, index: 0}"
    cat > "$dir/robot.yaml" <<EOF
# generated by stack_sim.sh: simulated $role $ns, PX4 SITL over UDP $aport
robot: {id: $id, namespace: $ns, hardware: sim}
$team
ros: {domain_id: $dom}
fc: {enabled: true, transport: udp, udp_port: $aport, px4_namespace: ""}
zenoh: {role: $role, connect: ["tcp/127.0.0.1:7447"], listen_address: 127.0.0.1, listen_port: $zport, multicast_scouting: false}
EOF
    cat > "$dir/stack.env" <<EOF
COMPOSE_PROJECT_NAME=castor-stack-sim-$ns
CASTOR_TAG=$TAG
CASTOR_ROBOT_CONFIG=$dir/robot.yaml
CASTOR_RUN_DIR=$dir/run
CASTOR_LOG_DIR=$dir/log
CASTOR_MODELS_DIR=$dir/models
CASTOR_TAKEOFF_HEIGHT=$TAKEOFF_HEIGHT
EOF
    # PX4 SITL instance (id-1): same domain, own agent port, no namespace (/fmu/... as on hardware)
    printf '%s ROS_DOMAIN_ID=%s PX4_UXRCE_DDS_PORT=%s PX4_UXRCE_DDS_NS=\n' "$((id - 1))" "$dom" "$aport" >> "$STATE/px4.env"
}

case "$cmd" in
up)
    # The model, its rig from the assets (checked), the drone count and the take-off height.
    check=(python3 "$HERE/rig_check.py" --shell)
    [ -n "$MODEL" ] && check+=(--model "$MODEL")
    [ -n "${CASTOR_TAKEOFF_HEIGHT:-}" ] && check+=(--takeoff-height "$CASTOR_TAKEOFF_HEIGHT")
    plan="$("${check[@]}")" || exit 2
    MODEL_ID=$(sed -n 's/^MODEL_ID=//p' <<<"$plan"); MODEL_DIR=$(sed -n 's/^MODEL_DIR=//p' <<<"$plan")
    RIG=$(sed -n 's/^RIG=//p' <<<"$plan"); DRONES=$(sed -n 's/^DRONES=//p' <<<"$plan")
    TAKEOFF_HEIGHT=$(sed -n 's/^TAKEOFF_HEIGHT=//p' <<<"$plan")
    echo "==> model $MODEL_ID ($MODEL_DIR), rig $RIG, $DRONES drones, take-off height $TAKEOFF_HEIGHT m"
    # Stacks from an earlier run (their bridges mount run/ directories that are about to be replaced).
    [ -d "$STATE" ] && "$0" down >/dev/null 2>&1 || true
    rm -rf "$STATE"; mkdir -p "$STATE/gcs/run"
    : > "$STATE/px4.env"
    printf 'MODEL_ID=%s\nRIG=%s\nDRONES=%s\nTAKEOFF_HEIGHT=%s\n' "$MODEL_ID" "$RIG" "$DRONES" "$TAKEOFF_HEIGHT" \
        > "$STATE/model.env"
    for i in $(seq 1 "$DRONES"); do
        write_robot "drone$i" "$i" $((20 + i)) $((7447 + i)) $((8887 + i)) drone $((i - 1))
        mkdir -p "$STATE/drone$i/models/$MODEL_ID"
        cp -r "$MODEL_DIR/." "$STATE/drone$i/models/$MODEL_ID/"
        echo "$MODEL_ID" > "$STATE/drone$i/models/DEFAULT"
    done
    if [ "$PAYLOAD" -eq 1 ]; then
        p=$((DRONES + 1))
        write_robot payload "$p" $((20 + p)) $((7447 + p)) $((8887 + p)) payload 0
    fi
    cat > "$STATE/gcs/robot.yaml" <<EOF
robot: {id: 100, namespace: gcs, hardware: laptop}
team: {size: 1, index: 0}
ros: {domain_id: 20}
fc: {enabled: false}
zenoh: {role: ground_station, listen_address: 127.0.0.1, listen_port: 7447, multicast_scouting: false}
EOF
    echo "==> ground station (domain 20, zenoh 127.0.0.1:7447)"
    CASTOR_TAG=$TAG CASTOR_ROBOT_CONFIG="$STATE/gcs/robot.yaml" CASTOR_RUN_DIR="$STATE/gcs/run" CASTOR_TAKEOFF_HEIGHT=$TAKEOFF_HEIGHT \
        "${COMPOSE[@]}" -p castor-stack-sim-gcs up -d --force-recreate zenoh-bridge
    for d in $(robots); do
        ns=$(basename "$d")
        echo "==> $ns ($(sed -n 's/^ros: //p' "$d/robot.yaml"), $(grep -o 'udp_port: [0-9]*' "$d/robot.yaml"))"
        "${COMPOSE[@]}" --env-file "$d/stack.env" up -d --force-recreate
    done
    echo "PX4 SITL environment per instance: $STATE/px4.env"
    echo "Simulator: make sim-pegasus-ros2$([ -n "$MODEL" ] && echo " MODEL=$MODEL")   (same model: rig $RIG)"
    ;;
takeoff | land | mission | watch | planning)
    team "$cmd" $(drones)
    ;;
goal)
    [ $# -ge 3 ] || { echo "usage: stack_sim.sh goal X Y Z [YAW_DEG]" >&2; exit 2; }
    team goal "$1" "$2" "$3" "${4:-0}" $(drones)
    ;;
status)
    [ -f "$STATE/model.env" ] && tr '\n' ' ' < "$STATE/model.env" && echo
    docker ps --filter "label=com.docker.compose.project" --format '{{.Label "com.docker.compose.project"}}\t{{.Names}}\t{{.Status}}' \
        | grep '^castor-stack-sim-' | sort
    ;;
down)
    for d in $(robots); do "${COMPOSE[@]}" --env-file "$d/stack.env" down; done
    CASTOR_TAKEOFF_HEIGHT=0 "${COMPOSE[@]}" -p castor-stack-sim-gcs down
    ;;
*) sed -n '2,36p' "$0" | sed 's/^# \?//'; exit 2 ;;
esac
