<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>castor_vehicle_interface</name>
  <version>0.1.0</version>
  <description>PX4 uXRCE-DDS topics to CASTOR ENU topics, and ENU setpoints to PX4 (off by default).</description>
  <maintainer email="kiran.g@radskunkworks.com">Kiran Gunathilaka</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>px4_msgs</depend>
  <depend>castor_interfaces</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
