#!/bin/bash
# Software in the loop on one machine: one onboard stack per simulated flight
# controller, exactly as each drone's Pi would run it, plus a ground station.
#
#   components/simulation/sil/sil.sh up [--drones N] [--payload] [--tag TAG]
#   components/simulation/sil/sil.sh status | down
#
# What makes it faithful to N separate Pis on one host:
#   - every robot gets its own ROS 2 domain (drone i: 20+i, payload: after the
#     drones), so no DDS traffic passes between robots inside the host;
#   - every robot has its own zenoh bridge on 127.0.0.1:7447+i, connected to the
#     ground station's bridge (domain 20, 127.0.0.1:7447): inter-robot traffic
#     crosses zenoh with the same allow-lists as in flight;
#   - every robot's vehicle container runs its own XRCE agent on UDP 8888+i-1,
#     and PX4 SITL instance i-1 is pointed at it (and at the robot's domain)
#     through environment variables PX4's rcS already reads (written to
#     <state>/px4.env for the simulator to use);
#   - the same images and docker-compose.prod.yml as a Pi, one compose project
#     per robot (castor-sil-<namespace>), each with its own run/log/model dirs.
#
# State lives in $CASTOR_SIL_DIR (default .sil/ in the repo, gitignored).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
STATE="${CASTOR_SIL_DIR:-$ROOT/.sil}"
COMPOSE=(docker compose -f "$ROOT/docker/docker-compose.prod.yml")
DRONES=3 PAYLOAD=0 TAG="${CASTOR_TAG:-local}"

cmd="${1:-}"; shift || true
while [ $# -gt 0 ]; do
    case "$1" in
        --drones) DRONES="$2"; shift 2 ;;
        --payload) PAYLOAD=1; shift ;;
        --tag) TAG="$2"; shift 2 ;;
        *) echo "unknown option '$1'" >&2; exit 2 ;;
    esac
done

# robot <namespace> <id> <domain> <bridge port> <agent port> <role> <team index>
write_robot() {
    local ns=$1 id=$2 dom=$3 zport=$4 aport=$5 role=$6 idx=$7 dir="$STATE/$1"
    mkdir -p "$dir/run" "$dir/log" "$dir/models"
    local team="team: {size: $DRONES, index: $idx}"
    [ "$role" = payload ] && team="team: {size: 1, index: 0}"
    cat > "$dir/robot.yaml" <<EOF
# generated by sil.sh: simulated $role $ns, PX4 SITL over UDP $aport
robot: {id: $id, namespace: $ns, hardware: sim}
$team
ros: {domain_id: $dom}
fc: {enabled: true, transport: udp, udp_port: $aport, px4_namespace: ""}
zenoh: {role: $role, connect: ["tcp/127.0.0.1:7447"], listen_address: 127.0.0.1, listen_port: $zport, multicast_scouting: false}
EOF
    cat > "$dir/stack.env" <<EOF
COMPOSE_PROJECT_NAME=castor-sil-$ns
CASTOR_TAG=$TAG
CASTOR_ROBOT_CONFIG=$dir/robot.yaml
CASTOR_RUN_DIR=$dir/run
CASTOR_LOG_DIR=$dir/log
CASTOR_MODELS_DIR=$dir/models
EOF
    # PX4 SITL instance (id-1): same domain, own agent port, no namespace (/fmu/... as on hardware)
    printf '%s ROS_DOMAIN_ID=%s PX4_UXRCE_DDS_PORT=%s PX4_UXRCE_DDS_NS=\n' "$((id - 1))" "$dom" "$aport" >> "$STATE/px4.env"
}

robots() { find "$STATE" -mindepth 2 -maxdepth 2 -name stack.env -printf '%h\n' 2>/dev/null | sort; }

case "$cmd" in
up)
    rm -rf "$STATE"; mkdir -p "$STATE/gcs/run"
    : > "$STATE/px4.env"
    for i in $(seq 1 "$DRONES"); do
        write_robot "drone$i" "$i" $((20 + i)) $((7447 + i)) $((8887 + i)) drone $((i - 1))
    done
    if [ "$PAYLOAD" -eq 1 ]; then
        p=$((DRONES + 1))
        write_robot payload "$p" $((20 + p)) $((7447 + p)) $((8887 + p)) payload 0
    fi
    cat > "$STATE/gcs/robot.yaml" <<EOF
robot: {id: 100, namespace: gcs, hardware: laptop}
team: {size: 1, index: 0}
ros: {domain_id: 20}
fc: {enabled: false}
zenoh: {role: ground_station, listen_address: 127.0.0.1, listen_port: 7447, multicast_scouting: false}
EOF
    echo "==> ground station (domain 20, zenoh 127.0.0.1:7447)"
    CASTOR_TAG=$TAG CASTOR_ROBOT_CONFIG="$STATE/gcs/robot.yaml" CASTOR_RUN_DIR="$STATE/gcs/run" \
        "${COMPOSE[@]}" -p castor-sil-gcs up -d zenoh-bridge
    for d in $(robots); do
        ns=$(basename "$d")
        echo "==> $ns ($(sed -n 's/^ros: //p' "$d/robot.yaml"), $(grep -o 'udp_port: [0-9]*' "$d/robot.yaml"))"
        "${COMPOSE[@]}" --env-file "$d/stack.env" up -d
    done
    echo "PX4 SITL environment per instance: $STATE/px4.env"
    ;;
status)
    docker ps --filter "label=com.docker.compose.project" --format '{{.Label "com.docker.compose.project"}}\t{{.Names}}\t{{.Status}}' \
        | grep '^castor-sil-' | sort
    ;;
down)
    for d in $(robots); do "${COMPOSE[@]}" --env-file "$d/stack.env" down; done
    "${COMPOSE[@]}" -p castor-sil-gcs down
    ;;
*) sed -n '2,22p' "$0" | sed 's/^# \?//'; exit 2 ;;
esac
