#!/bin/bash
# Software in the loop on one machine: one onboard stack per simulated flight
# controller, exactly as each drone's Pi would run it, plus a ground station.
#
#   components/simulation/sil/sil.sh up [--drones N] [--payload] [--tag TAG] [--model NAME/VERSION|DIR|FILE.onnx]
#   components/simulation/sil/sil.sh status | down
#
# Mission (the system layer's mission node, from the ground station's domain 20):
#   sil.sh takeoff                    PX4 Takeoff mode, arm, climb to the take-off height, hand over to RAPTOR
#   sil.sh goal X Y Z [YAW_DEG]       payload goal, world frame (ENU, m); taken once the team is at height
#   sil.sh land                       stop the policy, PX4 Land
#   sil.sh mission                    print every drone's mission state
#
# What makes it faithful to N separate Pis on one host:
#   - every robot gets its own ROS 2 domain (drone i: 20+i, payload: after the
#     drones), so no DDS traffic passes between robots inside the host;
#   - every robot has its own zenoh bridge on 127.0.0.1:7447+i, connected to the
#     ground station's bridge (domain 20, 127.0.0.1:7447): inter-robot traffic
#     crosses zenoh with the same allow-lists as in flight;
#   - every robot's vehicle container runs its own XRCE agent on UDP 8888+i-1,
#     and PX4 SITL instance i-1 is pointed at it (and at the robot's domain)
#     through environment variables PX4's rcS already reads (written to
#     <state>/px4.env for the simulator to use);
#   - the same images and docker-compose.prod.yml as a Pi, one compose project
#     per robot (castor-sil-<namespace>), each with its own run/log/model dirs;
#   - the policy is a model package (models/README.md): --model, default
#     models/DEFAULT, copied into every drone's models dir (mounted at
#     /var/lib/castor/models, so it overrides the image's copy, no rebuild);
#     docker-compose.sil.yml only lets the vehicle component forward setpoints
#     and commands to its PX4 SITL (off on a Pi). CASTOR_TAKEOFF_HEIGHT (2.0 m).
#
# State lives in $CASTOR_SIL_DIR (default .sil/ in the repo, gitignored).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
MODELS="$ROOT/models"
STATE="${CASTOR_SIL_DIR:-$ROOT/.sil}"
COMPOSE=(docker compose -f "$ROOT/docker/docker-compose.prod.yml" -f "$ROOT/docker/docker-compose.sil.yml")
DRONES=3 PAYLOAD=0 TAG="${CASTOR_TAG:-local}" MODEL=""

cmd="${1:-}"; shift || true
if [ "$cmd" != goal ]; then
    while [ $# -gt 0 ]; do
        case "$1" in
            --drones) DRONES="$2"; shift 2 ;;
            --payload) PAYLOAD=1; shift ;;
            --tag) TAG="$2"; shift 2 ;;
            --model) MODEL="$2"; shift 2 ;;
            *) echo "unknown option '$1'" >&2; exit 2 ;;
        esac
    done
fi

# A ROS 2 command on the ground station's domain, from the system image.
gcs_ros() {
    docker run --rm --network host --ipc host -e ROS_DOMAIN_ID=20 -v "$STATE/gcs/robot.yaml:/etc/castor/robot.yaml:ro" \
        "${CASTOR_REGISTRY:-ghcr.io/fyp-uav-entc-22}/castor-system:$TAG" "$@"
}
# Publish a few times, after the bridge has matched: a single sample can leave before
# the route to the drones exists.
team_pub() { gcs_ros ros2 topic pub -w 1 --times 3 "$@" >/dev/null && echo "sent $1"; }

# robot <namespace> <id> <domain> <bridge port> <agent port> <role> <team index>
write_robot() {
    local ns=$1 id=$2 dom=$3 zport=$4 aport=$5 role=$6 idx=$7 dir="$STATE/$1"
    mkdir -p "$dir/run" "$dir/log" "$dir/models"
    local team="team: {size: $DRONES, index: $idx}"
    [ "$role" = payload ] && team="team: {size: 1, index: 0}"
    cat > "$dir/robot.yaml" <<EOF
# generated by sil.sh: simulated $role $ns, PX4 SITL over UDP $aport
robot: {id: $id, namespace: $ns, hardware: sim}
$team
ros: {domain_id: $dom}
fc: {enabled: true, transport: udp, udp_port: $aport, px4_namespace: ""}
zenoh: {role: $role, connect: ["tcp/127.0.0.1:7447"], listen_address: 127.0.0.1, listen_port: $zport, multicast_scouting: false}
EOF
    cat > "$dir/stack.env" <<EOF
COMPOSE_PROJECT_NAME=castor-sil-$ns
CASTOR_TAG=$TAG
CASTOR_ROBOT_CONFIG=$dir/robot.yaml
CASTOR_RUN_DIR=$dir/run
CASTOR_LOG_DIR=$dir/log
CASTOR_MODELS_DIR=$dir/models
EOF
    # PX4 SITL instance (id-1): same domain, own agent port, no namespace (/fmu/... as on hardware)
    printf '%s ROS_DOMAIN_ID=%s PX4_UXRCE_DDS_PORT=%s PX4_UXRCE_DDS_NS=\n' "$((id - 1))" "$dom" "$aport" >> "$STATE/px4.env"
}

# The model package to fly: --model as <name>/<version> under models/ or a package directory, else models/DEFAULT.
# Prints "<id> <dir>".
model_package() {
    local m="${MODEL:-$(cat "$MODELS/DEFAULT")}"
    if [ -f "$MODELS/$m/model.yaml" ]; then
        echo "$m $MODELS/$m"
    elif [ -f "$m/model.yaml" ]; then
        echo "sil/$(basename "$(realpath "$m")") $(realpath "$m")"
    else
        echo "model '$m' not found: give <name>/<version> under models/, a package directory or a .onnx" >&2
        return 1
    fi
}

robots() { find "$STATE" -mindepth 2 -maxdepth 2 -name stack.env -printf '%h\n' 2>/dev/null | sort; }

case "$cmd" in
up)
    if [[ "$MODEL" != *.onnx ]]; then
        read -r MODEL_ID MODEL_DIR < <(model_package) || exit 2
        echo "==> model $MODEL_ID ($MODEL_DIR)"
    fi
    rm -rf "$STATE"; mkdir -p "$STATE/gcs/run"
    : > "$STATE/px4.env"
    for i in $(seq 1 "$DRONES"); do
        write_robot "drone$i" "$i" $((20 + i)) $((7447 + i)) $((8887 + i)) drone $((i - 1))
        if [[ "$MODEL" == *.onnx ]]; then
            cp "$MODEL" "$STATE/drone$i/models/policy.onnx"   # bare, no manifest: the runner's defaults
        else
            mkdir -p "$STATE/drone$i/models/$MODEL_ID"
            cp -r "$MODEL_DIR/." "$STATE/drone$i/models/$MODEL_ID/"
            echo "$MODEL_ID" > "$STATE/drone$i/models/DEFAULT"
        fi
    done
    if [ "$PAYLOAD" -eq 1 ]; then
        p=$((DRONES + 1))
        write_robot payload "$p" $((20 + p)) $((7447 + p)) $((8887 + p)) payload 0
    fi
    cat > "$STATE/gcs/robot.yaml" <<EOF
robot: {id: 100, namespace: gcs, hardware: laptop}
team: {size: 1, index: 0}
ros: {domain_id: 20}
fc: {enabled: false}
zenoh: {role: ground_station, listen_address: 127.0.0.1, listen_port: 7447, multicast_scouting: false}
EOF
    echo "==> ground station (domain 20, zenoh 127.0.0.1:7447)"
    CASTOR_TAG=$TAG CASTOR_ROBOT_CONFIG="$STATE/gcs/robot.yaml" CASTOR_RUN_DIR="$STATE/gcs/run" \
        "${COMPOSE[@]}" -p castor-sil-gcs up -d zenoh-bridge
    for d in $(robots); do
        ns=$(basename "$d")
        echo "==> $ns ($(sed -n 's/^ros: //p' "$d/robot.yaml"), $(grep -o 'udp_port: [0-9]*' "$d/robot.yaml"))"
        "${COMPOSE[@]}" --env-file "$d/stack.env" up -d
    done
    echo "PX4 SITL environment per instance: $STATE/px4.env"
    ;;
takeoff | land)
    team_pub /team/command castor_interfaces/msg/TeamCommand "{command: $cmd}"
    ;;
goal)
    [ $# -ge 3 ] || { echo "usage: sil.sh goal X Y Z [YAW_DEG]" >&2; exit 2; }
    read -r qz qw < <(python3 -c "import math; y = math.radians(${4:-0}); print(math.sin(y / 2), math.cos(y / 2))")
    team_pub /team/goal geometry_msgs/msg/PoseStamped \
        "{header: {frame_id: map}, pose: {position: {x: $1, y: $2, z: $3}, orientation: {z: $qz, w: $qw}}}"
    ;;
mission)
    for d in $(robots); do
        ns=$(basename "$d")
        [ "$ns" = payload ] && continue
        printf '%s: ' "$ns"
        gcs_ros timeout 5 ros2 topic echo --once --field state "/$ns/system/mission" 2>/dev/null | head -1 || echo "(no message)"
    done
    ;;
status)
    docker ps --filter "label=com.docker.compose.project" --format '{{.Label "com.docker.compose.project"}}\t{{.Names}}\t{{.Status}}' \
        | grep '^castor-sil-' | sort
    ;;
down)
    for d in $(robots); do "${COMPOSE[@]}" --env-file "$d/stack.env" down; done
    "${COMPOSE[@]}" -p castor-sil-gcs down
    ;;
*) sed -n '2,32p' "$0" | sed 's/^# \?//'; exit 2 ;;
esac
